export const FILTER_VERSION = 'precision-v1'

export const TRUSTED_AUTHOR_HANDLES = [
  'infoca.bsky.social',
  'aemet.bsky.social',
  'renfe.bsky.social',
  'adif.bsky.social',
  'dgt.bsky.social',
  'guardiacivil.bsky.social',
  'proteccioncivil.bsky.social',
] as const

export const TRUSTED_AUTHOR_DIDS = [] as const

export const TRUSTED_LINK_DOMAINS = [
  'aemet.es',
  'dgt.es',
  'larioja.org',
  'juntadeandalucia.es',
  'renfe.com',
  'adif.es',
  'madrid.es',
  'barcelona.cat',
  'gencat.cat',
  '112canarias.com',
  '112cmadrid.es',
] as const

export const SPAIN_INSTITUTION_SIGNALS = [
  'aemet',
  'dgt',
  'guardia civil',
  'proteccion civil',
  'emergencias 112',
  '112',
  'infoca',
  'renfe',
  'adif',
  'samur',
  'sos rioja',
  'mossos',
  'ertzaintza',
  'servei catala de transit',
  'transit',
  'bomberos',
] as const

export const SPAIN_GEO_SIGNALS = [
  'espana',
  'madrid',
  'barcelona',
  'valencia',
  'sevilla',
  'zaragoza',
  'malaga',
  'murcia',
  'granada',
  'cadiz',
  'cordoba',
  'logrono',
  'calahorra',
  'la rioja',
  'andalucia',
  'andaluz',
  'andaluzas',
  'cataluna',
  'galicia',
  'asturias',
  'cantabria',
  'navarra',
  'aragon',
  'castilla y leon',
  'castilla-la mancha',
  'extremadura',
  'baleares',
  'canarias',
  'tenerife',
  'gran canaria',
  'bizkaia',
  'gipuzkoa',
  'alava',
  'bilbao',
  'vitoria',
  'donostia',
  'alicante',
  'castellon',
  'tarragona',
  'girona',
  'lleida',
  'almeria',
  'jaen',
  'huelva',
  'toledo',
  'valladolid',
  'burgos',
  'salamanca',
  'badajoz',
  'caceres',
  'oviedo',
  'gijon',
  'santander',
  'pamplona',
] as const

export const MOBILITY_TERMS = [
  'trafico',
  'circulacion',
  'carretera',
  'autovia',
  'autopista',
  'carril',
  'via',
  'vias',
  'ruta',
  'acceso',
  'desvio',
  'desplaza',
  'desplazate',
  'desplazarte',
  'desplazarse',
  'desplazamiento',
  'desplazamientos',
  'moverse',
  'movilidad',
  'viaje',
  'viajes',
  'trayecto',
  'trayectos',
  'tren',
  'ferrocarril',
  'cercanias',
  'metro',
  'tranvia',
  'bus',
  'autobus',
  'autocar',
  'estacion',
  'aeropuerto',
  'vuelo',
  'puente',
  'tunel',
  'peaje',
  'salida',
  'entrada',
] as const

export const INCIDENT_TERMS = [
  'accidente',
  'colision',
  'choque',
  'atropello',
  'incidencia',
  'incidente',
  'corte',
  'cerrada',
  'cerrado',
  'bloqueado',
  'bloqueada',
  'averia',
  'retraso',
  'demora',
  'cancelacion',
  'interrumpida',
  'interrumpido',
  'retenciones',
  'retencion',
] as const

export const HAZARD_TERMS = [
  'lluvia',
  'lluvias',
  'chubasco',
  'chubascos',
  'tormenta',
  'tormentoso',
  'granizo',
  'nieve',
  'nevadas',
  'hielo',
  'niebla',
  'nieblas',
  'inundacion',
  'inundaciones',
  'riada',
  'desbordamiento',
  'deslizamiento',
  'desprendimiento',
  'viento',
  'racha',
  'rachas',
  'ventisca',
  'vendaval',
  'temporal',
  'incendio',
  'humo',
] as const

export const WARNING_CUES = [
  'aviso',
  'avisos',
  'alerta',
  'alertas',
  'precaucion',
  'precauciones',
  'prudencia',
] as const

export const STRONG_TRANSPORT_INCIDENT_PHRASES = [
  'accidente de trafico',
  'accidente en la carretera',
  'carretera cortada',
  'corte de trafico',
  'corte total de trafico',
  'retencion de trafico',
  'retenciones en',
  'atasco en',
  'carril cortado',
  'via cortada',
  'vias cortadas',
  'circulacion interrumpida',
  'servicio interrumpido',
  'servicio suspendido',
  'tren detenido',
  'averia en cercanias',
  'incidencia en cercanias',
  'incidencia en renfe',
  'atropello',
  'colision',
  'choque multiple',
  'autovia cortada',
  'autopista cortada',
  'desplazate con precaucion',
  'evita desplazamientos',
  'eviten desplazamientos',
  'evitar desplazamientos',
  'precaucion en carretera',
  'extrema la precaucion en carretera',
  'circulacion suspendida',
  'afecta a la circulacion',
  'afectan a la circulacion',
  'dificulta la circulacion',
  'dificultan la circulacion',
  'complicaciones en la circulacion',
  'vias intransitables',
  'carreteras intransitables',
] as const

export const HARD_DENY_PHRASES = [
  'atasco judicial',
  'retencion de liquidos',
  'atencion medica',
  'desastre de temporada',
  'guerra diplomatica',
  'tribunales',
  'suplemento de hierro',
  'diagnosticos',
  'tratamientos',
  'temporada marcada',
] as const

export const NEGATIVE_CONTEXT_PHRASES = [
  'judicial',
  'tribunal',
  'tribunales',
  'asuntos civiles',
  'conciliacion',
  'medica',
  'medico de cabecera',
  'hierro',
  'lacteo',
  'regla',
  'nba',
  'bucks',
  'pelicans',
  'temporada',
  'competicion',
  'netanyahu',
  'israel',
  'diplomatica',
  'hipocresia',
] as const

export const SPAIN_ROAD_PATTERN =
  /\b(?:a|ap|n|m|c|cv|rm|tf|gc|ac|ag|gr|ma|se|co|ca|hu|ab|to|sa|bu|lo|na|bi|ss|po|ou|lu|ex)-?\d{1,4}\b/
